### PR TITLE
Fix expired Discord link

### PR DESCRIPTION
**Pull request by mcauser**

### CODE REVIEW

**Comment by wallarug** [comment]
Hi Mike,

Thank you for the fix!  How can I confirm this is the correct Discord link?  Can you post a source?

**Comment by mcauser** [comment]
Hi @wallarug

Link to the discussion with Dan on Discord #circuitpython channel:
https://discord.com/channels/327254708534116352/327298996332658690/785491728634478592

Me:
```
The discord invite link used in a lot of community bundles readmes is showing up as expired. eg. discord / nBQh6qu
eg. https://github.com/barbudor/CircuitPython_TMP75
Should be changed to .gg/adafruit?
```
(To avoid my comment being deleted by the bots, i had to change `discord.gg/nBQh6qu` to `discord / nBQh6qu`)

DanH:
```
The canonical link is https://adafru.it/discord. Could you file an issue on the community bundle to note this?
Thanks!
```

**Comment by wallarug** [comment]
Thanks Mike.

I am just very conscious of security around things like this.   

Thank you for going through and pulling it up on all the community repositories.  Much appreciated.

**Comment by mcauser** [comment]
Always a good idea to verify patches like this.
Cheers, Mike

**Pull request merged**
